# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from meshrun.coordinator.proto import coordinator_pb2 as coordinator__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coordinator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorServiceStub(object):
    """── Service Definition ──────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/meshrun.coordinator.CoordinatorService/Register',
                request_serializer=coordinator__pb2.RegisterRequest.SerializeToString,
                response_deserializer=coordinator__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/meshrun.coordinator.CoordinatorService/Heartbeat',
                request_serializer=coordinator__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=coordinator__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ConfirmReady = channel.unary_unary(
                '/meshrun.coordinator.CoordinatorService/ConfirmReady',
                request_serializer=coordinator__pb2.ConfirmReadyRequest.SerializeToString,
                response_deserializer=coordinator__pb2.ConfirmReadyResponse.FromString,
                _registered_method=True)
        self.Deregister = channel.unary_unary(
                '/meshrun.coordinator.CoordinatorService/Deregister',
                request_serializer=coordinator__pb2.DeregisterRequest.SerializeToString,
                response_deserializer=coordinator__pb2.DeregisterResponse.FromString,
                _registered_method=True)
        self.RequestRoute = channel.unary_unary(
                '/meshrun.coordinator.CoordinatorService/RequestRoute',
                request_serializer=coordinator__pb2.RequestRouteRequest.SerializeToString,
                response_deserializer=coordinator__pb2.RequestRouteResponse.FromString,
                _registered_method=True)
        self.ReportFailure = channel.unary_unary(
                '/meshrun.coordinator.CoordinatorService/ReportFailure',
                request_serializer=coordinator__pb2.ReportFailureRequest.SerializeToString,
                response_deserializer=coordinator__pb2.ReportFailureResponse.FromString,
                _registered_method=True)
        self.TriggerAssignment = channel.unary_unary(
                '/meshrun.coordinator.CoordinatorService/TriggerAssignment',
                request_serializer=coordinator__pb2.TriggerAssignmentRequest.SerializeToString,
                response_deserializer=coordinator__pb2.TriggerAssignmentResponse.FromString,
                _registered_method=True)
        self.AcceptLayerAssignment = channel.unary_unary(
                '/meshrun.coordinator.CoordinatorService/AcceptLayerAssignment',
                request_serializer=coordinator__pb2.AcceptLayerAssignmentRequest.SerializeToString,
                response_deserializer=coordinator__pb2.AcceptLayerAssignmentResponse.FromString,
                _registered_method=True)
        self.GetNetworkStatus = channel.unary_unary(
                '/meshrun.coordinator.CoordinatorService/GetNetworkStatus',
                request_serializer=coordinator__pb2.GetNetworkStatusRequest.SerializeToString,
                response_deserializer=coordinator__pb2.GetNetworkStatusResponse.FromString,
                _registered_method=True)


class CoordinatorServiceServicer(object):
    """── Service Definition ──────────────────────────────────────────────────────

    """

    def Register(self, request, context):
        """Worker node self-registers with capacity info.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Periodic health signal from worker node.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmReady(self, request, context):
        """Worker signals shard loaded and ready to serve.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deregister(self, request, context):
        """Worker node graceful removal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestRoute(self, request, context):
        """Client requests execution path + session key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportFailure(self, request, context):
        """Worker reports downstream node failure.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerAssignment(self, request, context):
        """Admin triggers layer assignment computation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptLayerAssignment(self, request, context):
        """Coordinator pushes assignment to worker (via worker's gRPC address).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetworkStatus(self, request, context):
        """Get full network status (for CLI and dashboard).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=coordinator__pb2.RegisterRequest.FromString,
                    response_serializer=coordinator__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=coordinator__pb2.HeartbeatRequest.FromString,
                    response_serializer=coordinator__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ConfirmReady': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmReady,
                    request_deserializer=coordinator__pb2.ConfirmReadyRequest.FromString,
                    response_serializer=coordinator__pb2.ConfirmReadyResponse.SerializeToString,
            ),
            'Deregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Deregister,
                    request_deserializer=coordinator__pb2.DeregisterRequest.FromString,
                    response_serializer=coordinator__pb2.DeregisterResponse.SerializeToString,
            ),
            'RequestRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRoute,
                    request_deserializer=coordinator__pb2.RequestRouteRequest.FromString,
                    response_serializer=coordinator__pb2.RequestRouteResponse.SerializeToString,
            ),
            'ReportFailure': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportFailure,
                    request_deserializer=coordinator__pb2.ReportFailureRequest.FromString,
                    response_serializer=coordinator__pb2.ReportFailureResponse.SerializeToString,
            ),
            'TriggerAssignment': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerAssignment,
                    request_deserializer=coordinator__pb2.TriggerAssignmentRequest.FromString,
                    response_serializer=coordinator__pb2.TriggerAssignmentResponse.SerializeToString,
            ),
            'AcceptLayerAssignment': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptLayerAssignment,
                    request_deserializer=coordinator__pb2.AcceptLayerAssignmentRequest.FromString,
                    response_serializer=coordinator__pb2.AcceptLayerAssignmentResponse.SerializeToString,
            ),
            'GetNetworkStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworkStatus,
                    request_deserializer=coordinator__pb2.GetNetworkStatusRequest.FromString,
                    response_serializer=coordinator__pb2.GetNetworkStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meshrun.coordinator.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meshrun.coordinator.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService(object):
    """── Service Definition ──────────────────────────────────────────────────────

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshrun.coordinator.CoordinatorService/Register',
            coordinator__pb2.RegisterRequest.SerializeToString,
            coordinator__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshrun.coordinator.CoordinatorService/Heartbeat',
            coordinator__pb2.HeartbeatRequest.SerializeToString,
            coordinator__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshrun.coordinator.CoordinatorService/ConfirmReady',
            coordinator__pb2.ConfirmReadyRequest.SerializeToString,
            coordinator__pb2.ConfirmReadyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshrun.coordinator.CoordinatorService/Deregister',
            coordinator__pb2.DeregisterRequest.SerializeToString,
            coordinator__pb2.DeregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshrun.coordinator.CoordinatorService/RequestRoute',
            coordinator__pb2.RequestRouteRequest.SerializeToString,
            coordinator__pb2.RequestRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportFailure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshrun.coordinator.CoordinatorService/ReportFailure',
            coordinator__pb2.ReportFailureRequest.SerializeToString,
            coordinator__pb2.ReportFailureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerAssignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshrun.coordinator.CoordinatorService/TriggerAssignment',
            coordinator__pb2.TriggerAssignmentRequest.SerializeToString,
            coordinator__pb2.TriggerAssignmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptLayerAssignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshrun.coordinator.CoordinatorService/AcceptLayerAssignment',
            coordinator__pb2.AcceptLayerAssignmentRequest.SerializeToString,
            coordinator__pb2.AcceptLayerAssignmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNetworkStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshrun.coordinator.CoordinatorService/GetNetworkStatus',
            coordinator__pb2.GetNetworkStatusRequest.SerializeToString,
            coordinator__pb2.GetNetworkStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
